Repository ORNL/DataFed, pull requests merged in 2024-11, with the labels that each got.

#1035 Update admin installation documentation
  CHANGELOG.md
  doc_source/index.rst
  doc_source/source/admin/install_bare_metal.rst
  doc_source/source/admin/install_docker.rst
  doc_source/source/index.rst
Labels: Type: Docs - User

#1034 Feature 1005 - Consolidate development environment setup into admin scripts
  CHANGELOG.md
  doc_source/index.rst
  doc_source/source/dev/environment_setup.rst
  doc_source/source/index.rst
Labels: Type: Docs - User

#1054 1053 enable foxx tests in ci pipeline
  .gitlab/end_to_end.yml
  CHANGELOG.md
  CMakeLists.txt
  docker/entrypoint_foxx.sh
Labels: Component: Database, Type: Test

#1088 Add documentation about running DataFed Python package from source repo
  python/datafed_pkg/README
Labels: Type: Docs - Code

#1096 1057 trigger running foxx tests as part of ci
  .gitlab/common.yml
  .gitlab/end_to_end.yml
  CHANGELOG.md
  CMakeLists.txt
  doc_source/index.rst
  doc_source/source/admin/install_bare_metal.rst
  doc_source/source/admin/install_docker.rst
  doc_source/source/dev/environment_setup.rst
  doc_source/source/index.rst
  docker/entrypoint_foxx.sh
  repository/docker/entrypoint_authz.sh
  repository/docker/entrypoint_repo.sh
Labels: Type: Test

#1062 1055 fix foxx setup script
  core/database/tests/test_setup.sh
  scripts/dependency_install_functions.sh
Labels: Type: Test

#1098 Switch from using latest to CI_COMMIT_SHA
  .gitlab/end_to_end.yml
Labels: Type: Bug

#1094 make harbor script more robust to error response returned by api
  .gitlab/build/build_core_image.yml
  .gitlab/build/build_foxx_image.yml
  .gitlab/build/build_gcs_base_image.yml
  .gitlab/build/build_gcs_image.yml
  .gitlab/build/build_repo_image.yml
  .gitlab/build/build_ws_image.yml
  .gitlab/build/force_build_core_image.yml
  .gitlab/build/force_build_foxx_image.yml
  .gitlab/build/force_build_gcs_base_image.yml
  .gitlab/build/force_build_gcs_image.yml
  .gitlab/build/force_build_repo_image.yml
  .gitlab/build/force_build_ws_image.yml
  .gitlab/common.yml
  .gitlab/end_to_end.yml
  .gitlab/stage_build_base.yml
  .gitlab/stage_image_check.yml
  scripts/ci_harbor_artifact_count.sh
Labels: Type: Bug

#1092 Cleanup echo statements and make image tags explicit
  compose/metadata/build_metadata_images_for_compose.sh
  scripts/compose_build_images.sh
Labels: Type: Refactor

#1064 1056 foxx test script fix
  .gitlab/end_to_end.yml
  core/database/tests/test_foxx.sh
  core/database/tests/test_setup.sh
  docker/entrypoint_foxx.sh
  scripts/dependency_install_functions.sh
  scripts/install_foxx.sh
Labels: Type: Test

#1068 1065 fix ci cleanup script
  .gitlab/stage_clear_cache.yml
  scripts/ci_purge_images.sh
Labels: Type: Bug

#1079 1077 refactor support esm deprecate commonjs syntax
  web/datafed-ws.js
  web/package.json.in
  web/test/util.test.js
  web/version.js.in
Labels: Component: Web UI, Type: Refactor

#1112 Removed --no-cache flag
  scripts/compose_build_images.sh
Labels: Type: Bug

#1125 Remove overwrite of PATH
  docker/Dockerfile.foxx
Labels: Component: Build

#1129 1121 fix undefined build var in dockerfile
  core/docker/Dockerfile
  docker/Dockerfile.dependencies
  docker/Dockerfile.runtime
Labels: Component: Build

#1133 Add check for running container
  .gitlab/end_to_end.yml
Labels: Type: Bug, Component: Build

#1139 1128 Fix GCS Container json permission issues
  repository/docker/Dockerfile.gcs
  repository/docker/entrypoint_authz.sh
Labels: Component: Build

#1131 1130 bug entrypoint error ignoring errors
  .gitlab/end_to_end.yml
  repository/docker/Dockerfile.gcs
  repository/docker/entrypoint_authz.sh
  scripts/globus/setup_globus.sh
Labels: Component: Build
