Repository ORNL/DataFed, pull requests merged in 2024-12, with the labels that each got.

#1151 Throw error if variable is not defined properly
  scripts/dependency_install_functions.sh
Labels: Component: Build

#1153 Upgrade dependency of curl to 8.11
  scripts/dependency_versions.sh
Labels: Component: Build

#1163 Remove line split
  tests/end-to-end/setup.sh
Labels: Type: Bug

#1134 1114 add web unit testing to ci
  .gitlab-ci.yml
  .gitlab/build/build_core_image.yml
  .gitlab/build/build_foxx_image.yml
  .gitlab/build/build_gcs_base_image.yml
  .gitlab/build/build_gcs_image.yml
  .gitlab/build/build_repo_image.yml
  .gitlab/build/build_ws_image.yml
  .gitlab/build/force_build_core_image.yml
  .gitlab/build/force_build_foxx_image.yml
  .gitlab/build/force_build_gcs_base_image.yml
  .gitlab/build/force_build_gcs_image.yml
  .gitlab/build/force_build_repo_image.yml
  .gitlab/build/force_build_ws_image.yml
  .gitlab/common.yml
  .gitlab/stage_build_base.yml
  .gitlab/stage_image_check.yml
  .gitlab/stage_unit.yml
  scripts/compose_build_images.sh
Labels: Type: New Feature, Component: Build

#1157 Add scripts for locating globus and gss api libraries
  CMakeLists.txt
  cmake/GSSAPI.cmake
  cmake/GlobusCommon.cmake
  scripts/install_authz_dependencies.sh
Labels: Component: Build

#1167 Add missing comment on env variable
  .gitlab/common.yml
Labels: Type: Docs - Code

#1158 1154 feature add unit test authz
  repository/gridftp/globus5/authz/CMakeLists.txt
  repository/gridftp/globus5/authz/tests/CMakeLists.txt
  repository/gridftp/globus5/authz/tests/unit/CMakeLists.txt
  repository/gridftp/globus5/authz/tests/unit/test_getVersion.cpp
Labels: Component: Build

#1161 1159 refactor authz cpp file
  repository/gridftp/globus5/authz/source/AuthzWorker.cpp
  repository/gridftp/globus5/authz/source/AuthzWorker.hpp
  repository/gridftp/globus5/authz/tests/unit/CMakeLists.txt
  repository/gridftp/globus5/authz/tests/unit/test_AuthzWorker.cpp
Labels: Component: GridFTP Auth Module

#1048 created a test class header for database api
  core/server/DatabaseAPI.hpp
  core/server/tests/unit/test_DatabaseAPI.cpp
Labels: Type: Bug

#1176 Remove problematic curl dump flag
  core/database/tests/test_setup.sh
  scripts/dependency_install_functions.sh
Labels: Type: Bug, Component: Database, Component: Build, Type: Test, Component: Scripts

#1175 Add -e back to core/database/test/scripts
  .gitlab/end_to_end.yml
  core/database/tests/test_foxx.sh
  core/database/tests/test_setup.sh
  core/database/tests/test_teardown.sh
  scripts/dependency_install_functions.sh
Labels: Type: Bug, Priority: High, Component: Build, Type: Test

#1160 1106 updated proto messages for setting token
  common/proto/common/SDMS.proto
  common/proto/common/SDMS_Auth.proto
Labels: Type: New Feature

#1178 [DLT-1149] Docker container GCS Collection Mount Bug
  CHANGELOG.md
  doc_source/source/admin/install_docker.rst
  scripts/globus/setup_collection_directory.sh
Labels: Type: Bug

#1192 Add DataFed dependency paths to curl so SSL will be found
  scripts/install_foxx.sh
Labels: Type: Refactor

#1186 Changes to allow for and auto generate debug log level
  .gitlab/end_to_end.yml
  common/include/common/DynaLog.hpp
  compose/all/compose.yml
  compose/metadata/compose.yml
  core/server/main.cpp
  docs/_sources/admin/general.rst.txt
  scripts/compose_generate_env.sh
  scripts/generate_core_config.sh
Labels: Component: Core, Component: Build, Component: Scripts

#1169 1168 feature add authz unit tests to ci
  .gitlab/stage_unit.yml
  CHANGELOG.md
  repository/docker/Dockerfile.gcs
  repository/gridftp/globus5/authz/tests/unit/test_AuthzWorker.cpp
Labels: Component: Build, Type: Test

#1188 Remove --dump flag
  scripts/install_foxx.sh
Labels: Type: Bug

#1187 1184 bug add set e foxx install
  .gitlab/build/build_foxx_image.yml
  CMakeLists.txt
  scripts/install_foxx.sh
Labels: Type: Bug
