Repository ORNL/DataFed, pull requests merged in 2025-08, with the labels that each got.

#1545 [DAPS-1529] Rework generate env script
  compose/all/generate_env.sh
  scripts/compose_generate_env.sh
Labels: Type: Refactor, Component: Scripts, Priority: Low

#1554 refactor - fix exception messages in resetKey, setAccessCount, getAcc…
  core/server/AuthMap.cpp
Labels: Type: Refactor

#1550 [DAPS-1549] Fix memory bug - move assignment operator and destructor for GlobusAPI to handle curl cleanup safely
  core/server/GlobusAPI.cpp
Labels: Component: Core

#1556 [DAPS-1551] ci job fail correctly on failed curl
  scripts/dependency_install_functions.sh
Labels: Component: CI

#1577 refactor: remove useless secret from user_router.
  core/database/foxx/api/user_router.js
Labels: Component: Database

#1592 [DAPS-1568] Formatting install scripts
  scripts/install_authz_dependencies.sh
  scripts/install_client_dependencies.sh
  scripts/install_core.sh
  scripts/install_core_dependencies.sh
  scripts/install_dependencies.sh
  scripts/install_docker_dependencies.sh
  scripts/install_docs_dependencies.sh
  scripts/install_end_to_end_test_dependencies.sh
  scripts/install_foxx.sh
  scripts/install_lego_and_certificates.sh
  scripts/install_python_client_dependencies.sh
  scripts/install_repo.sh
  scripts/install_repo_dependencies.sh
  scripts/install_ws.sh
  scripts/install_ws_dependencies.sh
Labels: Component: Scripts, Priority: Low

#1613 Formatting remaining scripts within DataFed
  common/tests/security/tcp_secure/test_tcp_insecure.sh
  common/tests/security/tcp_secure/test_tcp_secure.sh
  compose/all/cleanup_globus_files.sh
  compose/all/generate_env.sh
  compose/metadata/build_metadata_images_for_compose.sh
  compose/metadata/generate_build_args.sh
  compose/metadata/generate_env.sh
  compose/repo/cleanup_globus_files.sh
  compose/repo/generate_env.sh
  core/database/tests/test_fixture_setup.sh
  core/database/tests/test_foxx.sh
  core/database/tests/test_setup.sh
  core/docker/entrypoint.sh
  docker/entrypoint_foxx.sh
  python/docker/entrypoint.sh
  repository/docker/entrypoint_authz.sh
  repository/docker/entrypoint_repo.sh
  repository/gridftp/globus5/authz/tests/mock/mock_start.sh
  repository/gridftp/globus5/authz/tests/mock/mock_stop.sh
  tests/end-to-end/setup.sh
  web/docker/entrypoint.sh
Labels: Component: Scripts, Priority: Low

#1606 [DAPS-1605] feature openshift support foxx
  .gitlab/build/build_foxx_image.yml
  .gitlab/end_to_end.yml
  CMakeLists.txt
  compose/all/compose.yml
  compose/metadata/compose.yml
  core/server/CoreServer.cpp
  doc_source/source/dev/testing.rst
  docker/Dockerfile.foxx
  docker/entrypoint_foxx.sh
  scripts/install_foxx.sh
Labels: Component: Database, Type: Refactor, Priority: Medium

#1617 [DAPS-1616] [Common] fix: make system secret optional before removing completely.
  common/proto/common/SDMS_Auth.proto
Labels: Component: Web API

#1621 Permissions issues when attempting to remove Version.proto during build
  docker/Dockerfile.foxx
Labels: Type: Bug, Component: Build, Priority: Low
