Repository ORNL/DataFed, pull requests merged in 2025-05, with the labels that each got.

#1392 [DAPS-1388] Add GCP Support
  web/static/api.js
  web/static/components/endpoint-browse/index.js
  web/static/components/transfer/transfer-endpoint-manager.js
  web/static/models/endpoint-model.js
  web/test/endpoint-model.test.js
Labels: Priority: High, Component: Web API, Component: Web UI

#1404 1396 add missing python module
  scripts/dependency_install_functions.sh
Labels: Component: Build, Component: CI

#1414 Switch to using .tar file install of libsodium
  scripts/dependency_install_functions.sh
Labels: Component: Build, Type: Refactor, Component: CI

#1417 Changed install scripts to be consistent with new python installation method
  docker/Dockerfile.dependencies
  repository/docker/Dockerfile.gcs
  scripts/dependency_install_functions.sh
  scripts/install_authz_dependencies.sh
  scripts/install_client_dependencies.sh
  scripts/install_core_dependencies.sh
  scripts/install_repo_dependencies.sh
  scripts/install_ws_dependencies.sh
Labels: Component: Build, Component: CI

#1426 Fix docker logs output in end-to-end tests
  .gitlab/common.yml
Labels: Type: Bug, Component: CI

#1440 Upgrade formatter
  .github/workflows/apply-formatting.yml
Labels: Component: CI

#1433 [TASK] Update pull_request_template.md
  .github/pull_request_template.md
Labels: Type: Docs - User

#1419 [DAPS-1408] Provenance Visual Management (2/2)
  .github/workflows/unit-tests.yml
  web/package.json.in
  web/static/components/provenance/assets/arrow-markers.js
  web/static/components/provenance/customization_modal.js
  web/static/components/provenance/panel_graph.js
  web/static/components/provenance/state.js
  web/static/components/provenance/styles/customization_modal.css
  web/static/components/provenance/styles/graph_styles.css
  web/static/components/provenance/styles/theme-variables.css
  web/static/components/provenance/utils.js
  web/static/jquery-ui-dark/datafed.css
  web/static/jquery-ui-light/datafed.css
  web/test/components/provenance/state.test.js
  web/test/components/provenance/utils.test.js
  web/views/main.ect
Labels: Type: New Feature, Component: Web UI

#1431 [DAPS-1408] Provenance Visual Management Lint (1/2)
  .github/workflows/unit-tests.yml
  web/package.json.in
  web/static/components/provenance/assets/arrow-markers.js
  web/static/components/provenance/customization_modal.js
  web/static/components/provenance/panel_graph.js
  web/static/components/provenance/state.js
  web/static/components/provenance/styles/customization_modal.css
  web/static/components/provenance/styles/graph_styles.css
  web/static/components/provenance/styles/theme-variables.css
  web/static/components/provenance/utils.js
  web/static/jquery-ui-dark/datafed.css
  web/static/jquery-ui-light/datafed.css
  web/static/main_browse_tab.js
  web/static/panel_graph.js
  web/test/components/provenance/state.test.js
  web/test/components/provenance/utils.test.js
  web/views/main.ect
Labels: Component: Web UI, Type: Refactor

#1424 [DAPS-1395] Address Memory Leaks in Core Server
  CMakeLists.txt
  common/include/common/ICredentials.hpp
  common/include/common/IMessage.hpp
  common/include/common/IOperator.hpp
  common/include/common/IServer.hpp
  common/include/common/ISocket.hpp
  common/source/communicators/ZeroMQCommunicator.cpp
  common/source/communicators/ZeroMQCommunicatorSecure.cpp
  common/source/communicators/ZeroMQCommunicatorSecure.hpp
  common/source/credentials/ZeroMQSocketCredentials.hpp
  common/source/messages/GoogleProtoMessage.hpp
  common/source/operators/AuthenticationOperator.hpp
  common/source/operators/RouterBookKeepingOperator.hpp
  common/source/servers/Proxy.hpp
  common/source/servers/ProxyBasicZMQ.cpp
  common/source/servers/ProxyBasicZMQ.hpp
  common/source/sockets/ZeroMQSocket.hpp
  common/source/support/zeromq/Context.hpp
  common/tests/CMakeLists.txt
  common/tests/unit/CMakeLists.txt
  common/tests/unit/test_Buffer.cpp
  common/tests/unit/test_CommunicatorFactory.cpp
  common/tests/unit/test_Frame.cpp
  common/tests/unit/test_MessageFactory.cpp
  common/tests/unit/test_OperatorFactory.cpp
  common/tests/unit/test_ProtoBufFactory.cpp
  common/tests/unit/test_ProtoBufMap.cpp
  common/tests/unit/test_Proxy.cpp
  common/tests/unit/test_ProxyBasicZMQ.cpp
  core/server/tests/CMakeLists.txt
  core/server/tests/unit/CMakeLists.txt
  core/server/tests/unit/test_AuthMap.cpp
  core/server/tests/unit/test_AuthenticationManager.cpp
  repository/gridftp/globus5/authz/tests/unit/test_AuthzWorker.cpp
  repository/gridftp/globus5/authz/tests/unit/test_getVersion.cpp
Labels: Type: Bug, Priority: High
