Repository ORNL/DataFed, pull requests merged in 2025-02, with the labels that each got.

#1274 Fix confusion in key uses in end to end tests
  .gitlab/end_to_end.yml
Labels: Type: Bug

#1270 Add env var
  CHANGELOG.md
  compose/all/compose.yml
  compose/metadata/compose.yml
  docker/Dockerfile.foxx
  scripts/compose_generate_env.sh
Labels: Type: Bug

#1286 Update the schema documentation to improve the usability.
  doc_source/source/user/web/portal.rst
Labels: Type: Docs - User

#1289 Add github action for linting jupyter
  .flake8
  .github/workflows/format-check.yml
  .github/workflows/jupyternotebook-lint.yml
  CHANGELOG.md
  jupyter_notebooks/.flake8
  jupyter_notebooks/0_verify.ipynb
  jupyter_notebooks/1_Basics.ipynb
  jupyter_notebooks/1_Basics_with_Solutions.ipynb
  jupyter_notebooks/2_Data_Records.ipynb
  jupyter_notebooks/2_Data_Records_with_Solutions.ipynb
  jupyter_notebooks/3_Data_Transfer.ipynb
  jupyter_notebooks/3_Data_Transfer_with_Solutions.ipynb
  jupyter_notebooks/4_Collections_Queries.ipynb
  jupyter_notebooks/4_Collections_Queries_with_Solutions.ipynb
  jupyter_notebooks/5_Collaborative_Exercise.ipynb
  pyproject.toml
Labels: Type: Docs - User

#1320 hotfix port mapping
  scripts/generate_repo_config.sh
Labels: Component: Core, Component: Repository, Component: Build

#1326 Merge hotfixes into devel
  .github/workflows/format-check.yml
  .gitlab/build/build_foxx_image.yml
  .gitlab/build/build_gcs_base_image.yml
  .gitlab/build/build_ws_image.yml
  .gitlab/build/force_build_gcs_base_image.yml
  .gitlab/build/force_build_gcs_image.yml
  .gitlab/common.yml
  .gitlab/stage_clear_cache.yml
  CHANGELOG.md
  cmake/Version.cmake
  doc_source/source/dev/project.rst
  scripts/generate_core_config.sh
  scripts/generate_repo_config.sh
Labels: Type: Release

#1284 Feature DAPS 1215 foxx UserGetAccessTokenRequest mapped collection support
  CHANGELOG.md
  common/proto/common/SDMS_Auth.proto
  core/database/CMakeLists.txt
  core/database/foxx/api/lib/user_token.js
  core/database/foxx/api/support.js
  core/database/foxx/api/user_router.js
  core/database/foxx/manifest.json.in
  core/database/foxx/tests/globus_collection_fixture.js
  core/database/foxx/tests/user_fixture.js
  core/database/foxx/tests/user_router.test.js
  core/database/foxx/tests/user_token.test.js
  core/database/tests/test_fixture_setup.sh
  core/server/ClientWorker.cpp
  core/server/DatabaseAPI.cpp
  core/server/DatabaseAPI.hpp
  web/datafed-ws.js
Labels: Component: Database, Component: Core

#1242 [DLT-1110] Implement Consent Required Action (3/4 & 4/4)
  web/datafed-ws.js
  web/package.json.in
  web/services/auth/ConsentHandler.js
  web/services/auth/TokenHandler.js
  web/services/auth/constants.js
  web/static/api.js
  web/static/components/endpoint-browse/index.js
  web/static/components/endpoint-browse/styles.css
  web/static/components/transfer/transfer-endpoint-manager.js
  web/static/components/transfer/transfer-templates.js
  web/static/components/transfer/transfer-ui-manager.js
  web/static/dlg_ep_browse.js
  web/static/models/transfer-model.js
  web/static/util.js
  web/test/ConsentHandler.js
  web/test/api.test.js
  web/test/util.test.js
  web/views/main.ect
Labels: Type: Bug, Priority: High, Type: New Feature, Component: Web API, Component: Web UI, Type: Update

#1328 JSON parse error fix
  core/server/DatabaseAPI.cpp
  core/server/DatabaseAPI.hpp
Labels: Component: Core
